version: '3.8'

services:
  fos-award:
    build: .
    container_name: fos-award-show
    restart: unless-stopped
    ports:
      - "8088:80"       # Ubah ke "8080:80" jika port 80 sudah dipakai aplikasi lain di VPS